# @package method
name: mic_gmm
relation_mode: channel # Testing Channel Mode
setting: osda

# Backbone
backbone: se_resnet50 
se_reduction: 16

# Training Params
epochs: 10
iters_per_epoch: 50
lr: 0.01

# GMM Module Params
queue_size: 1024
attn_dim: 3072 

# MIC Params
mic_mask_ratio: 0.7

# Loss Weights
lambda_proto: 1.0 # Not used in code?
lambda_mic: 0.5
lambda_adapt: 1.0
lambda_ent: 0.1

# Testing Settings
unknown_threshold: 0.55
