# @package method
name: mic_gmm
relation_mode: soft_label # soft_label or channel
setting: osda

# Backbone
backbone: se_resnet50 # Using our custom wrapper inside the solver, but this might be for logging
se_reduction: 16

# Training Params
epochs: 100
iters_per_epoch: 100
lr: 0.01

# GMM Module Params
queue_size: 2048
attn_dim: 3072 # C3(1024) + C4(2048)

# MIC Params
mic_mask_ratio: 0.7

# Loss Weights
lambda_proto: 1.0
lambda_mic: 0.5
lambda_adapt: 0.3
lambda_ent: 0.1

# Testing Settings
unknown_threshold: 0.55
