name: prc

setting: msda
supported_settings: [msda]

backbone: resnet50
epochs: 20
lr: 0.01

temperature_start: 0.15
temperature_end: 0.10
consistency_start_epoch: 5
ramp_denom: 16.0
save_ckpt_after_epoch: 15

strong_aug: true
strong_train_aug: true
stratified_batch: true
