# @package _global_

method:
  name: rtda
  setting: osda
  supported_settings: [osda]
  
  # RTDA hyperparameters
  lr: 0.00005
  momentum: 0.9
  weight_decay: 0.0005
  nesterov: true
  head_lr_mult: 10.0
  
  epochs: 70
  
  warm_up_epoch: 3
  
  K_cluster: 20
