defaults:
  - _self_
  - dataset: office-31
  - method: ros
  # Enable colorlog for colored console output
  - override hydra/job_logging: colorlog

# Global parameters
batch_size: 64
num_workers: 8
device: auto  # auto, cuda, mps, cpu
seed: 42
exp_name: "test_run"

hydra:
  run:
    dir: ${src_dir:}/../results/${exp_name}/${now:%Y-%m-%d_%H-%M-%S}

  job:
    chdir: True
