name: DomainNet
root: data/domainnet

# Default domains
source: real
sources: []
target: sketch

# DomainNet has 345 classes (Index 0-344)
num_classes: 345
splits:
  csda:
    source: ${range:"0-344"}
    target: ${range:"0-344"}

  msda:
    source: ${range:"0-344"}
    target: ${range:"0-344"}
