name: PACS
root: data/pacs

# Default domains
source: photo
sources: []
target: sketch

# PACS has 7 classes (Index 0-6)
num_classes: 7
splits:
  csda:
    source: ${range:0-6}
    target: ${range:0-6}

  msda:
    source: ${range:0-6}
    target: ${range:0-6}
